### ISSUE TITLE
Option to disable dumping pre-existing badges

### ISSUE THREAD

**Issue by ihaveamac** [MrCheeze/GYTB#1]
some people might not want to keep the badges they already have (Nintendo Badge Arcade, already-installed custom ones, etc.), so a quick and easy way to delete the data or simply not dump it would be nice.

https://gbatemp.net/threads/nintendo-badge-arcade-hacking-full-documentation-and-progress.403183/page-11#post-5852648

**Comment by bahrymat** [comment]
Ok. With the next version, press L+R+X+Y on startup to delete preexisting badge extdata.

**Comment by MrCheeze** [comment]
Ok. With the next version, press L+R+X+Y on startup to delete preexisting badge extdata.
