### ISSUE TITLE
Error when loading exdata

### ISSUE THREAD

**Issue by realdemirHD** [MrCheeze/GYTB#41]
I load my badges and they all go through showing previews and such but when writing exdata it crashes giving me an error

**Comment by ChildishhAlbino** [comment]
~~I've got the same problem - updated to latest Luma and no help~~

EDIT: My issue was due to `preview.png` images in the folders that caused the number of badges to exceed 1000.

**Comment by realdemirHD** [comment]
damn, I don't have a preview.png

**Comment by ChildishhAlbino** [comment]
Make sure your Luma3ds is up to date and that you don't have any images that have a load of blank space in them - every 64x64 pixel square of the image will be separated into their own badges and that could be blowing up the number of badges

**Comment by realdemirHD** [comment]
damn I will check to see about the ones with blank space but pretty sure I have below 1000 even with them being split because it gets to the very end and says complete and then crashes

**Comment by realdemirHD** [comment]
Ok so I know this is really late but I had an image which was almost fully blank I removed it and it worked THANK YOU SO MUCH

**Comment by ChildishhAlbino** [comment]
Glad to hear it - please close the issue if everything is working as expected
