### ISSUE TITLE
.cia Error Message: "WHAT IS WRONG WITH THE ELF. 0000004f"

### ISSUE THREAD

**Issue by MattTheSpratt** [MrCheeze/GYTB#44]
3DS Version: 11.15.0-47E (with CFW installed)

Upon booting the program, it lists this message:
Extdata exists.
NNID found: XXXXXXXX (not going to risk showing my ID to the world)
Checking for preexisting Badge Arcade badges to dump...

And then it spools out a massive list of badge filenames, like so:
badges/Example badge.1234.0.png

with each filename followed by:
error 79; failed to open file for writing rgb565ToPNG? 0000004f

I'm not very experienced with CFW stuff on 3DS, so I don't know how to continue like this.

**Comment by MrCheeze** [comment]
Can you make a folder named badges - not sure where the cia version looks but probably at the root of the SD card

**Comment by MattTheSpratt** [comment]
Mine was settled inside G:\3ds\GYTB\badges alongside the .3dsx file, I'll try moving it up to the root of the SD card to see if that helps.

That seems to have done it! Thank you for the help!
