### ISSUE TITLE
Please make a github "Release" for your project.

### ISSUE THREAD

**Issue by ksanislo** [MrCheeze/GYTB#7]
If you post your project as a release, it can be automatically updated in the [3DS Homebrew Title Database](https://www.titledb.com/). As it stands, someone needs to manually enter each new release you make to keep things listed.

**Comment by MrCheeze** [comment]
chaoskagami's version is more up to date than my own, and realistically that's probably going to remain the case. It also has a release, so might as well put that in the database.

https://github.com/chaoskagami/GYTB/releases

**Comment by ksanislo** [comment]
I've switched the listed entry to chaoskagami's version.
