### ISSUE TITLE
Crashing when adding badges

### ISSUE THREAD

**Issue by fennectech** [MrCheeze/GYTB#9]
On 11.2 luma3ds it crashes when adding this library of badges 
[badges.zip](https://github.com/MrCheeze/GYTB/files/691844/badges.zip)

**Comment by MrCheeze** [comment]
You cannot have more than 1000 badges, this is a limit built into the system.

**Comment by fennectech** [comment]
ok   sorry

**Comment by MrCheeze** [comment]
Nah, dont be, it's not like the program itself is clear about it.

**Comment by fennectech** [comment]
its a cool tool    the 11.2 safehax downgrade was awesome!!
